postgresqldata:
  build: data-dockerfile
  volumes:
   - /datadump:/media/dbdump:rw

postgresql:
  build: postgres-dockerfile
  restart: unless-stopped
  env_file:
   - ./postgres-dockerfile/postgres.env
  volumes:
   - /mnt/pgdata/pgdata:/var/lib/postgresql/data
  expose:
   - "5432"

musicbrainz:
  build: musicbrainz-dockerfile
  ports:
   - "5000:5000"
  volumes_from:
   - postgresqldata
  restart: unless-stopped
  environment: 
   - MUSICBRAINZ_USE_PROXY=1
  expose: 
   - "5000"
  links:
   - postgresql:db
   - search:search

indexer:
  build: indexer-dockerfile
  links:
   - postgresql:db
  volumes:
   - /mnt/data:/home/search/data

search:
  build: search-dockerfile
  restart: unless-stopped  
  expose:
   - "8080"
  volumes:
   - /mnt/data:/home/search/data
